### ISSUE TITLE
Add verify presentation page 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/edge-sandbox#471] opened 2020-08-14 06:07 UTC
Right now we see the json output. Make the page saying "Thanks your driving license is verfied" Now you can fill in the details to open the account. 

Also

failed to verify: {"checks":[{"check":"proof","error":"verifiable presentation proof validation error : verifiable credential proof validation error : JSON-LD doc has different structure after compaction"}]}

**Comment by llorllale** [comment] 2020-08-14 12:51
@talwinder50 this is a duplicate of #430

**Closed by llorllale** 2020-08-14 12:51 UTC
Labels: enhancement
